### ISSUE TITLE
SQLite 3.26.0 Support

### ISSUE THREAD

**Issue by cokuna-pavelkosolapov** [journeyapps/node-sqlcipher#12]
Hallo!

Could you please say, how about sqlite v3.26.0? 

Thanks

**Comment by kblum** [comment]
Support for SQLCipher 4.0.1 (based on SQLite 3.26.0) is in progress (#14).

**Comment by cokuna-pavelkosolapov** [comment]
Great. Thanks!

**Comment by cokuna-pavelkosolapov** [comment]
Hi guys! How about an npmjs update? 
https://www.npmjs.com/package/@journeyapps/sqlcipher it's still old version

**Comment by lemontea888** [comment]
> Hi guys! How about an npmjs update?
> https://www.npmjs.com/package/@journeyapps/sqlcipher it's still old version

I Modify the new version for node and Electron
https://github.com/lemontea888/node-sqlcipher-win

**Comment by rkistner** [comment]
SQLite 3.28.0 (SQLCipher 4.2) is now supported in release 4.0.0.
