### ISSUE TITLE
403 on downloading sqlcipher as dependency

### ISSUE THREAD

**Issue by Aentfs** [journeyapps/node-sqlcipher#13]
Hello,

while building `signal-desktop` on `Linux x64` the downloader can't access the prebuilt binaries or the source tar ball for `electron-v3`.

Those are the URLs returning 403:
https://journeyapps-node-binary.s3.amazonaws.com/@journeyapps/sqlcipher/v3.2.1/electron-v3.0-linux-x64.tar.gz

https://journeyapps-node-binary.s3.amazonaws.com/@journeyapps/sqlcipher/v3.2.1/electron-v3.0-linux-x64.tar.gz

**Comment by taigrr** [comment]
I came across this just now as well.

**Comment by taigrr** [comment]
@Aentfs although the packages are still 403'd, it looks like signal-desktop no longer relies on them. Refresh your package cache and update again, and it will build properly 😄

**Comment by rkistner** [comment]
Pre-built binaries are now available for version 4.0.0 for Electron 3, 4 and 5.
