### ISSUE TITLE
Can't open database file in Android

### ISSUE THREAD

**Issue by shanmukhateja** [journeyapps/node-sqlcipher#15]
Hi,
I am trying to import the database file in Android app however I get the error:

`net.sqlcipher.database.SQLiteException: file is not a database: , while compiling: select count(*) from sqlite_master;`

I also tried decrypting this test database file following the link [here](https://stackoverflow.com/questions/32100227/sqlcipher-how-to-import-a-sqlite3-database) but to no avail.

**Javascript code:**

```
const self = this
const sqlite3 = require('@journeyapps/sqlcipher').verbose()
const dbPath = 'path/metadata.db'
const db = new sqlite3.Database(dbPath)
// create syllabus table
      db.run("CREATE TABLE IF NOT EXISTS my_table (id TEXT, title TEXT)")
      // add new data
      let i=0
      for(i=0;i<self.sylList.length;i+=1) {
        const item = self.sylList[i]
        db.run("INSERT INTO my_table VALUES ($id, $title)", {
          $id: item.id,
          $title: item.title
        })
      }
```
**Android side:**

```
public static void getList(Context context) throws SQLiteException {
    SQLiteDatabase.loadLibs(context);
    final String dbFilePath = FileUtils.getMetadataFile();
    SQLiteDatabase database = SQLiteDatabase.
            openOrCreateDatabase(new File(dbFilePath), "12345678", null);
    Cursor cursor = database.rawQuery("SELECT * FROM my_table", null);
    while(cursor.moveToNext()) {
        Log.d(TAG, cursor.getString(1));
    }
}

```

Some help?

**Comment by rkistner** [comment]
While the database formats should be compatible, it depends on the exact library and cipher settings you're using on both sides. Supporting compatibility with a specific Android library / config is outside the scope of this project.
