### ISSUE TITLE
some dependence problem

### ISSUE THREAD

**Issue by 956237586** [journeyapps/node-sqlcipher#18]
1.iojs.lib location error
after install
.node-gyp\iojs-1.8.7\ia32\iojs.lib

compile
.node-gyp\iojs-1.8.7\x86\iojs.lib

2.upgrade binding.sln to vs2017 compatible
3.node_sqlite3 link error
change 
$(OutDir)obj\global_intermediate\sqlcipher-amalgamation-3020001\OpenSSL-Win64;%(AdditionalLibraryDirectories)
to
$(OutDir)obj\global_intermediate\sqlcipher-amalgamation-3020001\OpenSSL-Win32;%(AdditionalLibraryDirectories)

**Comment by rkistner** [comment]
You appear to be using `iojs-1.8.7`. See the README for the latest supported platforms.
