### ISSUE TITLE
the db file cannot open by sqlitestudio

### ISSUE THREAD

**Issue by alex8088** [journeyapps/node-sqlcipher#19]
why the db file cannot open by sqlitestudio

**Comment by kblum** [comment]
The DB file is encrypted using SQLCipher so you will need a client that can handle this. Here are some options: https://discuss.zetetic.net/t/management-interfaces-for-sqlcipher-databases/121

**Comment by alex8088** [comment]
sqlitestudio support for SQLCipher. you can try it.

**Comment by rkistner** [comment]
As long as the cipher settings match between the two, it should be possible to open the db file. That said, we cannot support third-party tools - open another issue if you cannot use the official sqlcipher CLI tool.
