### ISSUE TITLE
Fails to run with Electron 4

### ISSUE THREAD

**Issue by wuno** [journeyapps/node-sqlcipher#20]
Running this on Windows 10 with Electron 4.0.0 throws a build error. 

> Error output:
> node-pre-gyp WARN Tried to download(403): https://journeyapps-node-binary.s3.amazonaws.com/@journeyapps/sqlcipher/v3.2.1/electron-v4.0-win32-x64.tar.gz
> node-pre-gyp WARN Pre-built binaries not found for @journeyapps/sqlcipher@3.2.1 and electron@4.0.0 (electron-v4.0 ABI, unknown) (falling back to source compile with node-gyp)

Does this package plan to update for using newer version of Electron? We can see that it does work with Electron version 2.0.4 but that is fairly outdated at this point.

**Comment by lemontea888** [comment]
> Running this on Windows 10 with Electron 4.0.0 throws a build error.
> 
> > Error output:
> > node-pre-gyp WARN Tried to download(403): https://journeyapps-node-binary.s3.amazonaws.com/@journeyapps/sqlcipher/v3.2.1/electron-v4.0-win32-x64.tar.gz
> > node-pre-gyp WARN Pre-built binaries not found for @journeyapps/sqlcipher@3.2.1 and electron@4.0.0 (electron-v4.0 ABI, unknown) (falling back to source compile with node-gyp)
> 
> Does this package plan to update for using newer version of Electron? We can see that it does work with Electron version 2.0.4 but that is fairly outdated at this point.

I Modify the new version for node and Electron
https://github.com/lemontea888/node-sqlcipher-win

**Comment by rkistner** [comment]
Version 4.0.0 now has pre-built binaries for Electron 3, 4 and 5.
