### ISSUE TITLE
Error: /lib64/libstdc++.so.6: version `CXXABI_1.3.9' not found

### ISSUE THREAD

**Issue by fraazalam** [journeyapps/node-sqlcipher#27]
I’m using “https://www.npmjs.com/package/@journeyapps/sqlcipher 1” with node js on linux centos 7, but getting run time error : “Error: /lib64/libstdc++.so.6: version `CXXABI_1.3.9’ not found (required by /home/avista-dev/server/source/node_modules/@journeyapps/sqlcipher/lib/binding/node-v72-linux-x64/node_sqlite3.node)”

I don’t have any option to upgrade my Linux centos 7 or GCC.
current versions:
GCC 4.8.5
Linux centos 7 (core)
highest version of CXABI is 1.3.7

**Comment by rkistner** [comment]
Unfortunately we're not able to provide support for every Linux configuration.

It may be possible to install from source instead of using the pre-built binaries:

    npm install @journeyapps/sqlcipher --build-from-source

We'll also accept pull requests fixing the issue.
