### ISSUE TITLE
Module not found: Error: Can't resolve 'aws-sdk'

### ISSUE THREAD

**Issue by joeyer** [journeyapps/node-sqlcipher#28]
electron:4.2.2
在mac上编译报错，用node-sqlite3，在wabpack里加上
 externals: {
        sqlite3: 'commonjs2 sqlite3',
    },

可以忽略，但是你这个不知掉怎么忽略

我试过:
externals: {
       "journeyapps/sqlcipher": 'commonjs2 "journeyapps/sqlcipher"',
    },
或：
externals: {
       "journeyapps/sqlcipher": "journeyapps/sqlcipher',
    },

都无法避免报错

**Comment by rkistner** [comment]
`aws-sdk` isn't required if this package is installed as a node_module.

**Comment by justin-collins** [comment]
I am also getting this error. Package is definitely installed as a node_module
