### ISSUE TITLE
Worker_Threads: Unable to find dialect

### ISSUE THREAD

**Issue by Hirobreak** [journeyapps/node-sqlcipher#40]
Hello, I'm running a `worker_thread` that needs to read a copy of my encrypted database.

Unfortunately when I try to connect to my database I get the following error: `UnhandledPromiseRejectionWarning: Error: Unable to find dialect at @journeyapps/sqlcipher`.

This is my database setup

```
sequelize = new Sequelize(null, null, key, {
    dialect: 'sqlite',
    dialectModulePath: '@journeyapps/sqlcipher',
    storage: path,
    logging: false,
    transactionType: 'IMMEDIATE'
  });
```

I have been reading about this issue and it might be related to `Enabling Context-Awareness`, here's some info about it [Context-Awareness](https://github.com/nodejs/node/blob/master/doc/api/addons.md#context-aware-addons) and [Example of Context-Awareness Fix](https://github.com/schroffl/node-lzo/pull/11/files)

I'm running `Electron 8` which runs `Node 12.13.0` and I'm using `Sequelize 5.21.2` and `@journeyapps/sqlcipher 4.0.0`
I'm able to import any other module I use on the rest of my electron app but this one, any help would be much appreciated

**Comment by rkistner** [comment]
The current version does not support running with worker_thread.

The upstream [node-sqlcipher3](https://github.com/mapbox/node-sqlite3/) project had some recent changes that could fix the issue. The changes will be included here soon.

**Comment by rkistner** [comment]
This now does seem to work with `worker_thread` on Node 14 / N-API 6. Earlier versions may appear to work, but are likely to run into crashes.

Electron 10 is based on Node v12.16.3, so worker_threads will not work yet.

**Comment by rkistner** [comment]
Also note that there are more unresolved upstream issues related to worker_threads:

https://github.com/mapbox/node-sqlite3/issues/1381

Best is to track the issues there, and update the project here if there are any fixes.
