### ISSUE TITLE
Empty results if query starts on new line

### ISSUE THREAD

**Issue by Kepro** [journeyapps/node-sqlcipher#42]
WebSQL / Android / iOS SQLCipher works fine, but for electron (node.js integration) will return empty array if query stars on new line

```
db.run(`
SELECT * FROM TABLE
`);
```
return [];
```
db.run(`SELECT * FROM TABLE`);
```
will return data

**Comment by rkistner** [comment]
Thanks for logging the issue, but it is not considered a bug here.

**Comment by Kepro** [comment]
@rkistner because?

**Comment by rkistner** [comment]
The node bindings have a completely different API from other platforms, so it is not expected to behave the same.

It is not documented, but it is a requirement of this lib to have the query on a single line.

**Comment by Kepro** [comment]
Thank you for explanation! I was wondering if it's working that way...
