### ISSUE TITLE
Build for window fail on Mac

### ISSUE THREAD

**Issue by jianfenkezhan** [journeyapps/node-sqlcipher#46]
node: v12.13.x
electron: v8.2.5
Mac: macOS Catalina v10.15.5

@journeyapps/sqlcipher/lib/binding/electron-v8.2-win32-x64/node_sqlite3.node is not a valid Win32 application

**Comment by rkistner** [comment]
It is not currently supported to cross-compile.

The next version will include prebuilt binaries that should work on electron 8.2.x.

**Comment by jianfenkezhan** [comment]
Thanks for your reply really!  And then, I want to know the next version can supported to cross-compile? 
Anyway, Thanks again.  Waiting....

**Comment by rkistner** [comment]
I've never tested it, but it should be possible to cross-compile with electron when pre-built binaries are used. The latest release (5.0.0) uses N-API, which means you should be able to get a pre-built binary for any supported Electron or Node version.

If it still doesn't work, check that the architecture of the library matches your application. The "not a valid Win32 application" error is common if there is a mismatch, e.g. a 32-bit application attempting to use a 64-bit library.
