### ISSUE TITLE
N-API version

### ISSUE THREAD

**Issue by MigFerreira** [journeyapps/node-sqlcipher#53]
When installing on windows everything is fine, but on mac I get this:
`Cannot find module '.../node_modules/@journeyapps/sqlcipher/lib/binding/napi-v3-darwin-x64/node_sqlite3.node'`
And I have napi-v6-darwin-x64 in binding folder

In console I get this as well: `node-pre-gyp info This Node instance does not support builds for N-API version 6`

I even lowered node from 14.x to 12.18.4
Also Ive tried building from source and issue persists

Any advice?

**Comment by FTAndy** [comment]
same issue

**Comment by maitham** [comment]
+1

**Comment by Christilut** [comment]
Same problem on Electron 11 here. Any fix for this yet?

**Comment by rkistner** [comment]
Working to get a fix out in the next week or so.

**Comment by Christilut** [comment]
Actually I upgraded my Node from 12.13 to 12.20 and this error is gone, but now the build fails like in #63

**Comment by rkistner** [comment]
The general solution is:
1. Make sure the correct N-API version of the bindings is installed.
2. Don't rebuild with electron-forge or electron-rebuild.

For Electron 11+, use Node v10.20.0+ / v12.17.0+ / v14.0.0.
For Electron 10 and earlier, use an earlier Node version.
*Note: Just changing the node version is not sufficient - you may need to remove `node_modules` and install again.*

For more details see the new notes: https://github.com/journeyapps/node-sqlcipher/blob/3870217c1245dd4253e2bac2ea8d1d12a8c4a2b6/README.md#usage-with-electron-forge--electron-rebuild.
