### ISSUE TITLE
Version 5.0.0 doesn't work on Windows 10

### ISSUE THREAD

**Issue by vidyuthd** [journeyapps/node-sqlcipher#54]
Hi 

i am using v5.0.0 version, and not able to get past the keying while db setup, fails at the step where i m trying to key the sqlite database without any errors in logs.
```
  await instance.run(`PRAGMA key = "x'${key}'";`);
```

If I don't do the above step, everything works fine. Is this linked to [ISSUE 46](https://github.com/journeyapps/node-sqlcipher/issues/46) , because i had to rename napi folders v6 as v3 and make it run on windows

It works in Mac but not in Windows 10 (Parallels machine i have on my machine)

**Comment by FTAndy** [comment]
Got the same issue, call 
```javascript
 await instance.run(`PRAGMA key = "x'${key}'";`);
```
electron will crash

**Comment by FTAndy** [comment]
@vidyuthd I know how to fix it, try to run `electron-rebuild`, and change `node_modules\@journeyapps\sqlcipher\lib\binding\napi-v6-win32-x64` to `napi-v3-win32-x64`.

**Comment by rkistner** [comment]
I would recommend _not_ renaming that folder - it is likely to cause a crash. You need to get the correct bindings installed.

I've added new instructions on workarounds here: https://github.com/journeyapps/node-sqlcipher/blob/3870217c1245dd4253e2bac2ea8d1d12a8c4a2b6/README.md#usage-with-electron-forge--electron-rebuild
