### ISSUE TITLE
Pre-built Binaries Not Found. [Electron]

### ISSUE THREAD

**Issue by haykerman** [journeyapps/node-sqlcipher#6]
Getting this error message when trying to run npm install in Electron project.

> node-pre-gyp ERR! Pre-built binaries not found for @journeyapps/sqlcipher@3.2.0 and electron@2.0.4 (electron-v2.0 ABI, unknown) (falling back to source compile with node-gyp)

**Comment by rkistner** [comment]
We haven't published prebuilt binaries for electron 2.0 yet. This is just supposed to be a warning though - does the installation continue after the message?

**Comment by haykerman** [comment]
@rkistner , no. It fails and breaks the further setup. Additionally there's another error while running npm start. It says `Please install sqlite3 package manually`. I don't know if it's related to sqlcipher or not.

**Comment by rkistner** [comment]
Can you post the full log output? On which OS is this? There may be some native dependencies required to build from source.

**Comment by rkistner** [comment]
That looks like missing openssl, try installing with `brew install openssl`.

**Comment by haykerman** [comment]
Thank you, @rkistner! That resolved my issue.

**Comment by sincerefly** [comment]
@rkistner I hava the same problem, I use electron 2.0.0, os is windows7

I install openssl from https://slproweb.com/products/Win32OpenSSL.html
Win64 OpenSSL v1.0.2o
and add C:\OpenSSL-Win64\bin to the windows path
I use `yarn add @journeyapps/sqlcipher` and electron-builder's `"postinstall": "install-app-deps"` may auto build it

is there other build way or cmd to rebuild `@journeyapps/sqlcipher` for electron, thanks

Log:

> Error output:
warning ..\..\..\package.json: No license field
node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@0.6.39
node-pre-gyp info using node@8.11.3 | win32 | x64
node-pre-gyp http GET https://journeyapps-node-binary.s3.amazonaws.com/@journeyapps/sqlcipher/v3.2.0/electron-v2.0-win32
-x64.tar.gz
node-pre-gyp http 403 https://journeyapps-node-binary.s3.amazonaws.com/@journeyapps/sqlcipher/v3.2.0/electron-v2.0-win32
-x64.tar.gz
node-pre-gyp ERR! Tried to download(403): https://journeyapps-node-binary.s3.amazonaws.com/@journeyapps/sqlcipher/v3.2.0
/electron-v2.0-win32-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for @journeyapps/sqlcipher@3.2.0 and electron@2.0.0 (electron-v2.0 ABI, u
nknown) (falling back to source compile with node-gyp)
node-pre-gyp http 403 status code downloading tarball https://journeyapps-node-binary.s3.amazonaws.com/@journeyapps/sqlc
ipher/v3.2.0/electron-v2.0-win32-x64.tar.gz
gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.2
gyp info using node@8.11.3 | win32 | x64
gyp info ok
gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.2
gyp info using node@8.11.3 | win32 | x64
gyp info spawn C:\Python27\python.EXE
gyp info spawn args [ 'C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-G',
gyp info spawn args   'msvs_version=2015',
gyp info spawn args   '-I',
gyp info spawn args   'D:\\githome\\tray-with-sqlite\\node_modules\\@journeyapps\\sqlcipher\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\dongdong\\.electron-gyp\\iojs-2.0.0\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\dongdong\\.electron-gyp\\iojs-2.0.0',
gyp info spawn args   '-Dnode_gyp_dir=C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\Users\\dongdong\\.electron-gyp\\iojs-2.0.0\\<(target_arch)\\iojs.lib',
gyp info spawn args   '-Dmodule_root_dir=D:\\githome\\tray-with-sqlite\\node_modules\\@journeyapps\\sqlcipher',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'D:\\githome\\tray-with-sqlite\\node_modules\\@journeyapps\\sqlcipher\\build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info ok
gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.2
gyp info using node@8.11.3 | win32 | x64
gyp info spawn C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe
gyp info spawn args [ 'build/binding.sln',
gyp info spawn args   '/clp:Verbosity=minimal',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=x64' ]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe` fail
ed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:2
58:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node
-gyp\\bin\\node-gyp.js" "build" "--fallback-to-build" "--module=D:\\githome\\tray-with-sqlite\\node_modules\\@journeyapp
s\\sqlcipher\\lib\\binding\\electron-v2.0-win32-x64\\node_sqlite3.node" "--module_name=node_sqlite3" "--module_path=D:\\
githome\\tray-with-sqlite\\node_modules\\@journeyapps\\sqlcipher\\lib\\binding\\electron-v2.0-win32-x64"
gyp ERR! cwd D:\githome\tray-with-sqlite\node_modules\@journeyapps\sqlcipher
gyp ERR! node -v v8.11.3
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'node-gyp.cmd build --fallback-to-build --module=D:\githome\tray-with-s
qlite\node_modules\@journeyapps\sqlcipher\lib\binding\electron-v2.0-win32-x64\node_sqlite3.node --module_name=node_sqlit
e3 --module_path=D:\githome\tray-with-sqlite\node_modules\@journeyapps\sqlcipher\lib\binding\electron-v2.0-win32-x64' (1
)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (D:\githome\tray-with-sqlite\node_modules\node-pre-gyp\lib\util\
compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:126:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:925:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
node-pre-gyp ERR! System Windows_NT 6.1.7601
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "D:\\githome\\tray-with-sqlite\\node_modules\\node-pre-g
yp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd D:\githome\tray-with-sqlite\node_modules\@journeyapps\sqlcipher
node-pre-gyp ERR! node -v v8.11.3
node-pre-gyp ERR! node-pre-gyp -v v0.6.39
node-pre-gyp ERR! not ok
error Command failed with exit code 1.

    at ChildProcess.childProcess.once.code (D:\githome\tray-with-sqlite\node_modules\app-builder-lib\node_modules\builde
r-util\src\util.ts:251:14)
    at Object.onceWrapper (events.js:317:30)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Socket.stream.socket.on (internal/child_process.js:346:11)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at Pipe._handle.close [as _onclose] (net.js:557:12)
From previous event:
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
From previous event:
    at D:\githome\tray-with-sqlite\node_modules\app-builder-lib\src\util\yarn.ts:154:27
From previous event:
    at rebuild (D:\githome\tray-with-sqlite\node_modules\app-builder-lib\out\util\yarn.js:238:18)
    at D:\githome\tray-with-sqlite\node_modules\app-builder-lib\src\util\yarn.ts:20:11
From previous event:
    at installOrRebuild (D:\githome\tray-with-sqlite\node_modules\app-builder-lib\out\util\yarn.js:68:17)
    at D:\githome\tray-with-sqlite\node_modules\electron-builder\src\cli\install-app-deps.ts:56:9
    at Generator.next (<anonymous>)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
From previous event:
    at installAppDeps (D:\githome\tray-with-sqlite\node_modules\electron-builder\out\cli\install-app-deps.js:174:17)
    at main (D:\githome\tray-with-sqlite\node_modules\electron-builder\src\cli\install-app-deps.ts:65:10)
    at Object.<anonymous> (D:\githome\tray-with-sqlite\node_modules\electron-builder\src\cli\install-app-deps.ts:70:3)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.

**Comment by rkistner** [comment]
@sincerefly It seems like 3.2.1 which contains all the pre-built binaries was never published - I published it now - it should solve your issue.

If you want to rebuild from scratch, you specifically need Visual Studio 2015, not 2017.

If you are still running into issues, open a new issue.

**Comment by sincerefly** [comment]
@rkistner I try build it again, It's ok, thank you!
