### ISSUE TITLE
node-pre-gyp info This Node instance does not support builds for N-API version 6

### ISSUE THREAD

**Issue by ajmasia** [journeyapps/node-sqlcipher#68]
Fails on W10 with node v12.16.3

**Comment by rkistner** [comment]
Please check #65.

**Comment by ajmasia** [comment]
@rkistner In Mac works fine but no using W10. I'm using `yarn` any extra packages for yarn?

**Comment by ajmasia** [comment]
Hi @rkistner ahain,

I've created a playground repo to test the new version https://github.com/ajmasia/electron-sqlite-playground
When run dev server for windows, the app close after run:

![Capture](https://user-images.githubusercontent.com/23419327/106098777-e6508980-6139-11eb-8b5e-f89bda6db927.PNG)

I'm using Electron 9.0.0 and Node v10.19.0 that's support N_API 3

Dependence is built correctly:

![Capture1](https://user-images.githubusercontent.com/23419327/106099003-4810f380-613a-11eb-9498-b62d4e51798d.PNG)

On mac works fine, any iadea?

Thanks!

**Comment by rkistner** [comment]
Working on a fix for Windows. This is the same issue as in #67, so moving the discussion there.

Note that the issue title (`node-pre-gyp info This Node instance does not support builds for N-API version 6`) is unrelated to the actual crash - that's just an informational message.

**Comment by ajmasia** [comment]
Thanks, @rkistner for star working on this fix, and sorry for my mistake 😄
