### ISSUE TITLE
How to reduce the installation package after electron integrates @journeyapps/sqlcipher ?

### ISSUE THREAD

**Issue by dlliu114** [journeyapps/node-sqlcipher#82]
Installation package after electron integrates @journeyapps/sqlcipher is too large（102MB）.  Package after electron integrates sqlite3 just 60+MB. How to reduce package after integrates @journeyapps/sqlcipher ?
electron version: 10.1.5
@journeyapps/sqlcipher version: 5.2.0

**Comment by terry2010** [comment]
you could delete some folders and files after your compile,
 electron only need  these files ,maybe less?


├── binding.gyp
├── lib
│   ├── binding
│   │   └── napi-v6-darwin-x64
│   │       └── node_sqlite3.node
│   ├── index.js
│   ├── sqlite3-binding.js
│   ├── sqlite3.js
│   └── trace.js
├── package-lock.json
├── package.json
├── sqlite3.js

**Comment by rkistner** [comment]
When using a tool like `electron-builder`, you can configure it to exclude files. I'm using something like this:

```
files:
  - '**/*'
  - '!src/**'
  - '!**/*.{tlog,lastbuildstate,pdb,obj,lib,map,exp,vcxproj,vcxproj.filters}'
  - '!**/sqlcipher/deps'
  - '!**/binding/node-*'
```

**Comment by rkistner** [comment]
The package size should be reduced in v5.3.0.

**Comment by dlliu114** [comment]
> The package size should be reduced in v5.3.0.

Thank you very much
