### ISSUE TITLE
Install on macOS failing with error: unexpected unqualified-id

### ISSUE THREAD

**Issue by aguynamedben** [journeyapps/node-sqlcipher#83]
Hi, thank you for publishing this package. 🙏 

We recently started seeing an issue while building the node bindings for sqlcipher with the error message `error: unexpected unqualified-id`. We use a very similar setup internally to @journeyapps/sqlcipher, and 2 of our developers (myself included) just started seeing this (1 yesterday, 1 today). We think it's due to a macOS or XCode update, but we haven't been able to figure it out. It's preventing us from making new builds of our app. We're running the same commands on the same code that worked 2 days ago, but the rebuild steps are failing now.

It's also affecting @journeyapps/sqlcipher 4.1.0 (pre N-API) and 5.2.0 (w/ N-API) on my machine in our app which uses Electron 11.0.4.

We've tried manually compiling and linking to SQLCipher from within binding.gyp, and using this module, but it seems there's some core change with macOS or XCode (header files, dependencies, etc.) that's preventing the building of SQLCipher + node-sqlite3 + Electron.

Below is a screenshot of the error when I tried @journeyapps/sqlcipher 4.2.0 and Electron 11.0.4. We have a lot of experience building SQLCipher with node-sqlite3, and every method we know to try ends up with this error.

Please let us know if you start seeing this error or have any ideas of the root causes, workarounds, or fixes. 🙏  Thanks again!

Electron version: 11.0.4
@journeyapps/sqlcipher version: 4.1.0 or 5.2.0
macOS version: 11.3
Xcode version: Version 12.5 (12E262) - for potential dependencies/headers/gcc/etc.

![image](https://user-images.githubusercontent.com/107841/116627349-cf206400-a901-11eb-880f-f0cc6d2a7630.png)

**Comment by aguynamedben** [comment]
We tracked this down to something with Xcode 12.5. Removing Xcode 12.5 and reinstalling Xcode 12.4 set our macOS SDK back to the 11.1 version, which seems to work.

The developer and I that had this happen to us don't recall upgrading Xcode 🤷‍♂️ 

I really appreciate that this repo is here. We're very likely to switch our app to use SQLCipher from here, so we can help triage issues with the community you've gathered here. 🙏

**Comment by felixSchl** [comment]
We ran into this problem as well. The problem appears to be that with C++20 there's now a version header that gets included with `#include <version>`, but thanks to OSX's case-insensitive file system it ends up including the "VERSION" file extracted from the sqlcipher-amalgamation-3033000.tar.gz tarball, which - of course - is not valid C++. We work around it for now by simply removing the file from the tarball in our fork...
