### ISSUE TITLE
typescript support missing

### ISSUE THREAD

**Issue by mugi-luffy** [journeyapps/node-sqlcipher#86]
typescript support would be great or even type information through: [https://definitelytyped.org/](https://definitelytyped.org/)
Are there any plans for this in the future?

**Comment by rkistner** [comment]
Added in #91 / v5.3.0.

**Comment by mugi-luffy** [comment]
I just updated to the latest version 5.3.0, but vscode is still complaining about missing type definitions:

![image](https://user-images.githubusercontent.com/23312130/145837671-77fa54ae-c2a1-4f7c-9fa3-d0f3359e6d5c.png)

**Comment by rkistner** [comment]
Double check that you have 5.3.0, and reloading the project.

Also try this form:

```ts
import * as sqlcipher from '@journeyapps/sqlcipher';
```

**Comment by mugi-luffy** [comment]
thnx reloading the project worked
