### ISSUE TITLE
Crash running under electron 13

### ISSUE THREAD

**Issue by xudafeng** [journeyapps/node-sqlcipher#95]
When I use electron 13 to run on windows platform, the app failed with dlopen

**Comment by rkistner** [comment]
1. Which version of the library are you using? (Make sure you're using the latest one)
2. Do you have a full stack trace or logs?

**Comment by xudafeng** [comment]
@rkistner Thank you for your reply, the version I failed yesterday was 5.2.0, now I changed to 5.3.1, it works fine.
